name: Security Checks

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  call-security-scans:
    uses: dezerv/security-commons/.github/workflows/security-scans.yml@master
    secrets:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      SLACK_WEBHOOK_URL_SECURITY_COMMON_SCANS: ${{ secrets.SLACK_WEBHOOK_URL_SECURITY_COMMON_SCANS }}
